services:
  postgres:
    image: postgres:latest
    container_name: boilerplate_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boilerplate
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    container_name: boilerplate_redis
    ports:
      - '6379:6379'
